export const departamentosColombia = [
  "Amazonas",
  "Antioquia",
  "Arauca",
  "Atlántico",
  "Bolívar",
  "Boyacá",
  "Caldas",
  "Caquetá",
  "Casanare",
  "Cauca",
  "Cesar",
  "Chocó",
  "Córdoba",
  "Cundinamarca",
  "Guainía",
  "Guaviare",
  "Huila",
  "La Guajira",
  "Magdalena",
  "Meta",
  "Nariño",
  "Norte de Santander",
  "Putumayo",
  "Quindío",
  "Risaralda",
  "San Andrés y Providencia",
  "Santander",
  "Sucre",
  "Tolima",
  "Valle del Cauca",
  "Vaupés",
  "Vichada",
] as const;

export const ciudadesPorDepartamento: Record<(typeof departamentosColombia)[number], string[]> = {
  Amazonas: ["Leticia", "Puerto Nariño"],
  Antioquia: [
    "Medellín",
    "Bello",
    "Envigado",
    "Itagüí",
    "Rionegro",
    "Sabaneta",
    "Apartadó",
    "Turbo",
    "Copacabana",
    "La Ceja",
  ],
  Arauca: ["Arauca", "Arauquita", "Saravena", "Tame"],
  "Atlántico": ["Barranquilla", "Soledad", "Malambo", "Puerto Colombia", "Sabanalarga"],
  Bolívar: ["Cartagena", "Magangué", "Turbaco", "Arjona", "El Carmen de Bolívar"],
  Boyacá: ["Tunja", "Duitama", "Sogamoso", "Chiquinquirá", "Paipa"],
  Caldas: ["Manizales", "La Dorada", "Chinchiná", "Villamaría", "Riosucio"],
  Caquetá: ["Florencia", "San Vicente del Caguán", "Belén de los Andaquíes"],
  Casanare: ["Yopal", "Aguazul", "Villanueva", "Paz de Ariporo", "Tauramena"],
  Cauca: ["Popayán", "Santander de Quilichao", "Puerto Tejada", "Patía"],
  Cesar: ["Valledupar", "Aguachica", "Codazzi", "Bosconia", "Curumaní"],
  Chocó: ["Quibdó", "Istmina", "Condoto", "Tadó", "Acandí"],
  Córdoba: ["Montería", "Lorica", "Sahagún", "Cereté", "Montelíbano"],
  Cundinamarca: [
    "Bogotá",
    "Soacha",
    "Chía",
    "Zipaquirá",
    "Facatativá",
    "Girardot",
    "Mosquera",
    "Madrid",
    "Funza",
    "Fusagasugá",
  ],
  Guainía: ["Inírida"],
  Guaviare: ["San José del Guaviare", "Calamar", "Miraflores"],
  Huila: ["Neiva", "Pitalito", "Garzón", "La Plata", "Campoalegre"],
  "La Guajira": ["Riohacha", "Maicao", "Uribia", "Fonseca", "San Juan del Cesar"],
  Magdalena: ["Santa Marta", "Ciénaga", "Fundación", "El Banco", "Aracataca"],
  Meta: ["Villavicencio", "Acacías", "Granada", "Puerto López", "Restrepo"],
  Nariño: ["Pasto", "Ipiales", "Tumaco", "Túquerres", "Samaniego"],
  "Norte de Santander": ["Cúcuta", "Ocaña", "Pamplona", "Villa del Rosario", "Los Patios"],
  Putumayo: ["Mocoa", "Puerto Asís", "Orito", "Sibundoy"],
  Quindío: ["Armenia", "Calarcá", "La Tebaida", "Montenegro", "Quimbaya"],
  Risaralda: ["Pereira", "Dosquebradas", "Santa Rosa de Cabal", "La Virginia"],
  "San Andrés y Providencia": ["San Andrés", "Providencia"],
  Santander: ["Bucaramanga", "Floridablanca", "Girón", "Piedecuesta", "Barrancabermeja"],
  Sucre: ["Sincelejo", "Corozal", "Sampués", "San Marcos", "Tolú"],
  Tolima: ["Ibagué", "Espinal", "Melgar", "Honda", "Líbano"],
  "Valle del Cauca": [
    "Cali",
    "Palmira",
    "Buenaventura",
    "Tuluá",
    "Yumbo",
    "Buga",
    "Jamundí",
    "Cartago",
  ],
  Vaupés: ["Mitú"],
  Vichada: ["Puerto Carreño"],
};

export function getCitiesForDepartment(department: string) {
  if (!department || !(department in ciudadesPorDepartamento)) {
    return [];
  }

  return ciudadesPorDepartamento[department as keyof typeof ciudadesPorDepartamento];
}
