export type ImageSlot = {
  key: string;
  label: string;
  group: string;
  division: "Cauchos" | "Import" | "Innovation" | "Plastic" | "Energy" | "GEU";
  defaultSrc: string;
  dims: string;
  /** True for the mobile-only counterpart of a wide banner slot (same content, taller crop for small screens). */
  isMobile?: boolean;
};

export const IMAGE_SLOTS: ImageSlot[] = [
  { key: "banner-principal", label: "Banner principal", group: "Página de inicio", division: "Cauchos", defaultSrc: "/banner-geu-universal-de-cauchos.jpg", dims: "2048 × 768 px" },
  { key: "banner-principal-movil", label: "Banner principal (versión móvil)", group: "Página de inicio", division: "Cauchos", defaultSrc: "/banner-geu-universal-de-cauchos.jpg", dims: "1024 × 1024 px", isMobile: true },
  { key: "banner-marcas-promo", label: "Promociones y marcas", group: "Página de inicio", division: "Cauchos", defaultSrc: "/banner-universal-cauchos-new.jpg", dims: "2048 × 768 px" },
  { key: "oferta-cauchos-productos", label: "Oferta 1 · Productos de caucho", group: "Ofertas", division: "Cauchos", defaultSrc: "/offer-productos-caucho.png", dims: "1024 × 1792 px" },
  { key: "oferta-cauchos-industriales", label: "Oferta 2 · Cauchos industriales", group: "Ofertas", division: "Cauchos", defaultSrc: "/offer-cauchos-industriales.png", dims: "1024 × 1792 px" },
  { key: "oferta-mangueras-industriales", label: "Oferta 3 · Mangueras industriales", group: "Ofertas", division: "Cauchos", defaultSrc: "/offer-mangueras-industriales.png", dims: "1024 × 1792 px" },
  { key: "oferta-soportes-industriales", label: "Oferta 4 · Soportes industriales", group: "Ofertas", division: "Cauchos", defaultSrc: "/offer-soportes-industriales.png", dims: "1024 × 1792 px" },
  { key: "marca-destacada-perfiles", label: "Marca destacada 1 · Perfiles", group: "Marcas destacadas", division: "Cauchos", defaultSrc: "/featured-cauchos-temp.jpg", dims: "900 × 250 px" },
  { key: "marca-destacada-mangueras", label: "Marca destacada 2 · Mangueras", group: "Marcas destacadas", division: "Cauchos", defaultSrc: "/featured-cauchos-temp.jpg", dims: "900 × 250 px" },
  { key: "marca-destacada-laminas", label: "Marca destacada 3 · Láminas", group: "Marcas destacadas", division: "Cauchos", defaultSrc: "/featured-cauchos-temp.jpg", dims: "900 × 250 px" },
  { key: "marca-destacada-soportes", label: "Marca destacada 4 · Soportes", group: "Marcas destacadas", division: "Cauchos", defaultSrc: "/featured-cauchos-temp.jpg", dims: "900 × 250 px" },
  { key: "cauchos-nosotros-destacada-1", label: "Nosotros · Destacada 1", group: "Nosotros", division: "Cauchos", defaultSrc: "/cauchos-nosotros-galeria-1.jpg", dims: "900 × 675 px" },
  { key: "cauchos-nosotros-destacada-2", label: "Nosotros · Destacada 2", group: "Nosotros", division: "Cauchos", defaultSrc: "/cauchos-nosotros-galeria-2.jpg", dims: "900 × 675 px" },
  { key: "cauchos-nosotros-destacada-3", label: "Nosotros · Destacada 3", group: "Nosotros", division: "Cauchos", defaultSrc: "/cauchos-nosotros-galeria-3.jpg", dims: "900 × 675 px" },
  { key: "cauchos-nosotros-destacada-4", label: "Nosotros · Destacada 4", group: "Nosotros", division: "Cauchos", defaultSrc: "/cauchos-nosotros-galeria-4.jpg", dims: "900 × 675 px" },
  { key: "banner-categorias", label: "Banner de categorías", group: "Página de categorías", division: "Cauchos", defaultSrc: "/cauchos-category-banner.jpg", dims: "1920 × 217 px" },
  { key: "banner-categorias-movil", label: "Banner de categorías (versión móvil)", group: "Página de categorías", division: "Cauchos", defaultSrc: "/cauchos-category-banner.jpg", dims: "800 × 360 px", isMobile: true },
  { key: "categoria-alimentos", label: "Categoría · Alimentos, Farmacéuticos y cosméticos", group: "Categorías", division: "Cauchos", defaultSrc: "/subcategorias/alimentos.jpg", dims: "600 × 600 px" },
  { key: "categoria-agroindustria", label: "Categoría · Agroindustria", group: "Categorías", division: "Cauchos", defaultSrc: "/subcategorias/agroindustria.jpg", dims: "600 × 600 px" },
  { key: "categoria-petroleo", label: "Categoría · Petróleo, minería, gas, energías renovables y petroquímica", group: "Categorías", division: "Cauchos", defaultSrc: "/subcategorias/petroleo.jpg", dims: "600 × 600 px" },
  { key: "categoria-quimico", label: "Categoría · Químico, aseo y plásticos", group: "Categorías", division: "Cauchos", defaultSrc: "/subcategorias/quimico.jpg", dims: "600 × 600 px" },
  { key: "categoria-construccion", label: "Categoría · Construcción, infraestructura, obra civil, cemento y agregados", group: "Categorías", division: "Cauchos", defaultSrc: "/subcategorias/construccion.jpg", dims: "600 × 600 px" },
  { key: "categoria-transporte", label: "Categoría · Transporte, logística y puertos marítimos", group: "Categorías", division: "Cauchos", defaultSrc: "/subcategorias/transporte.jpg", dims: "600 × 600 px" },
  { key: "categoria-manufactura", label: "Categoría · Manufactura, metalmecánica, siderúrgica y textiles", group: "Categorías", division: "Cauchos", defaultSrc: "/subcategorias/manufactura.jpg", dims: "600 × 600 px" },
  { key: "categoria-ferreteria", label: "Categoría · Ferretería y otros", group: "Categorías", division: "Cauchos", defaultSrc: "/subcategorias/ferreteria.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-alimentos", label: "Subcategoría · Alimentos", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/alimentos.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-farmaceuticos", label: "Subcategoría · Farmacéuticos", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/farmaceuticos.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-cosmeticos", label: "Subcategoría · Cosméticos", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/cosmeticos.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-agroindustria", label: "Subcategoría · Agroindustria", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/agroindustria.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-petroleo", label: "Subcategoría · Petróleo", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/petroleo.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-mineria", label: "Subcategoría · Minería", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/mineria.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-gas", label: "Subcategoría · Gas", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/gas.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-energias-renovables", label: "Subcategoría · Energías renovables", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/energias-renovables.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-petroquimica", label: "Subcategoría · Petroquímica", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/petroquimica.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-quimico", label: "Subcategoría · Químico", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/quimico.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-aseo", label: "Subcategoría · Aseo", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/aseo.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-plasticos", label: "Subcategoría · Plásticos", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/plasticos.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-construccion", label: "Subcategoría · Construcción", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/construccion.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-infraestructura", label: "Subcategoría · Infraestructura", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/infraestructura.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-obra-civil", label: "Subcategoría · Obra civil", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/obra-civil.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-cemento", label: "Subcategoría · Cemento", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/cemento.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-agregados", label: "Subcategoría · Agregados", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/agregados.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-transporte", label: "Subcategoría · Transporte", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/transporte.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-logistica", label: "Subcategoría · Logística", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/logistica.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-puertos-maritimos", label: "Subcategoría · Puertos marítimos", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/puertos-maritimos.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-manufactura", label: "Subcategoría · Manufactura", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/manufactura.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-metalmecanica", label: "Subcategoría · Metalmecánica", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/metalmecanica.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-siderurgica", label: "Subcategoría · Siderúrgica", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/siderurgica.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-textiles", label: "Subcategoría · Textiles", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/textiles.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-ferreteria", label: "Subcategoría · Ferretería", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/ferreteria.jpg", dims: "600 × 600 px" },
  { key: "subcategoria-otros", label: "Subcategoría · Otros", group: "Subcategorías (menú)", division: "Cauchos", defaultSrc: "/subcategorias/otros.jpg", dims: "600 × 600 px" },
  { key: "import-principal", label: "Import · Banner principal", group: "Página de inicio", division: "Import", defaultSrc: "/geu-import-main-banner.jpg", dims: "1632 × 612 px" },
  { key: "import-principal-movil", label: "Import · Banner principal (versión móvil)", group: "Página de inicio", division: "Import", defaultSrc: "/geu-import-main-banner.jpg", dims: "1024 × 1024 px", isMobile: true },
  { key: "import-marcas-promo", label: "Import · Promociones y marcas", group: "Página de inicio", division: "Import", defaultSrc: "/geu-import-main-banner.jpg", dims: "2048 × 768 px" },
  { key: "import-cierre", label: "Import · Banner de cierre", group: "Página de inicio", division: "Import", defaultSrc: "/geu-import-main-banner.jpg", dims: "1920 × 217 px" },
  { key: "import-cierre-movil", label: "Import · Banner de cierre (versión móvil)", group: "Página de inicio", division: "Import", defaultSrc: "/geu-import-main-banner.jpg", dims: "800 × 360 px", isMobile: true },
  { key: "import-oferta-1", label: "Import · Oferta 1", group: "Ofertas", division: "Import", defaultSrc: "/geu-import-main-banner.jpg", dims: "1024 × 1792 px" },
  { key: "import-oferta-2", label: "Import · Oferta 2", group: "Ofertas", division: "Import", defaultSrc: "/home-import.png", dims: "1024 × 1792 px" },
  { key: "import-oferta-3", label: "Import · Oferta 3", group: "Ofertas", division: "Import", defaultSrc: "/import-hero-banner.png", dims: "1024 × 1792 px" },
  { key: "import-oferta-4", label: "Import · Oferta 4", group: "Ofertas", division: "Import", defaultSrc: "/import-hero-crop.png", dims: "1024 × 1792 px" },
  { key: "import-destacada-1", label: "Import · Destacada 1", group: "Marcas destacadas", division: "Import", defaultSrc: "/import-destacada-1.jpg", dims: "900 × 250 px" },
  { key: "import-destacada-2", label: "Import · Destacada 2", group: "Marcas destacadas", division: "Import", defaultSrc: "/import-destacada-2.jpg", dims: "900 × 250 px" },
  { key: "import-destacada-3", label: "Import · Destacada 3", group: "Marcas destacadas", division: "Import", defaultSrc: "/import-destacada-3.jpg", dims: "900 × 250 px" },
  { key: "import-destacada-4", label: "Import · Destacada 4", group: "Marcas destacadas", division: "Import", defaultSrc: "/import-destacada-4.jpg", dims: "900 × 250 px" },
  { key: "import-nosotros-1", label: "Nosotros · Destacada 1", group: "Nosotros", division: "Import", defaultSrc: "/import-destacada-1.jpg", dims: "900 × 675 px" },
  { key: "import-nosotros-2", label: "Nosotros · Destacada 2", group: "Nosotros", division: "Import", defaultSrc: "/import-destacada-2.jpg", dims: "900 × 675 px" },
  { key: "import-nosotros-3", label: "Nosotros · Destacada 3", group: "Nosotros", division: "Import", defaultSrc: "/import-destacada-3.jpg", dims: "900 × 675 px" },
  { key: "import-nosotros-4", label: "Nosotros · Destacada 4", group: "Nosotros", division: "Import", defaultSrc: "/import-destacada-4.jpg", dims: "900 × 675 px" },
  { key: "import-categoria-laminas", label: "Categoría · Láminas de caucho", group: "Categorías", division: "Import", defaultSrc: "/home-import.png", dims: "600 × 600 px" },
  { key: "import-categoria-empaquetaduras", label: "Categoría · Empaquetaduras", group: "Categorías", division: "Import", defaultSrc: "/home-import.png", dims: "600 × 600 px" },
  { key: "import-categoria-plasticos", label: "Categoría · Plásticos de Ingeniería", group: "Categorías", division: "Import", defaultSrc: "/home-import.png", dims: "600 × 600 px" },
  { key: "import-categoria-acoples-opw", label: "Categoría · Acoples OPW", group: "Categorías", division: "Import", defaultSrc: "/home-import.png", dims: "600 × 600 px" },
  { key: "import-categoria-acoples-hidraulicos", label: "Categoría · Acoples Hidráulicos", group: "Categorías", division: "Import", defaultSrc: "/home-import.png", dims: "600 × 600 px" },
  { key: "import-categoria-valvulas", label: "Categoría · Válvulas, acoples y racores", group: "Categorías", division: "Import", defaultSrc: "/home-import.png", dims: "600 × 600 px" },
  { key: "import-categoria-mangueras-hidraulicas", label: "Categoría · Mangueras Hidráulicas", group: "Categorías", division: "Import", defaultSrc: "/home-import.png", dims: "600 × 600 px" },
  { key: "import-categoria-mangueras-industriales", label: "Categoría · Mangueras Industriales", group: "Categorías", division: "Import", defaultSrc: "/home-import.png", dims: "600 × 600 px" },
  { key: "import-categoria-mangueras-pvc", label: "Categoría · Mangueras en PVC", group: "Categorías", division: "Import", defaultSrc: "/home-import.png", dims: "600 × 600 px" },
  { key: "import-categoria-mangueras-caucho-lona", label: "Categoría · Mangueras en caucho y lona", group: "Categorías", division: "Import", defaultSrc: "/home-import.png", dims: "600 × 600 px" },
  { key: "import-categoria-linea-neumatica", label: "Categoría · Línea Neumática", group: "Categorías", division: "Import", defaultSrc: "/home-import.png", dims: "600 × 600 px" },
  { key: "import-categoria-aislamientos-termicos", label: "Categoría · Aislamientos Térmicos", group: "Categorías", division: "Import", defaultSrc: "/home-import.png", dims: "600 × 600 px" },
  { key: "import-categoria-mercado-persa", label: "Categoría · Mercado Persa", group: "Categorías", division: "Import", defaultSrc: "/home-import.png", dims: "600 × 600 px" },
  { key: "import-categoria-autopartes", label: "Categoría · Autopartes", group: "Categorías", division: "Import", defaultSrc: "/home-import.png", dims: "600 × 600 px" },
  // ---- GEU Structure · Sitio público (/innovation) ----
  { key: "structure-hero", label: "Structure · Imagen del héroe", group: "Sitio Structure", division: "Innovation", defaultSrc: "/geu-structure-hero.jpg", dims: "1920 × 1280 px" },
  { key: "structure-producto-m24", label: "Structure · Producto M24 biposte", group: "Sitio Structure", division: "Innovation", defaultSrc: "/geu-structure-producto-m24.png", dims: "1536 × 864 px" },
  { key: "structure-viento-cfd", label: "Structure · Simulación CFD de viento", group: "Sitio Structure", division: "Innovation", defaultSrc: "/geu-structure-viento-cfd.png", dims: "1536 × 998 px" },
  { key: "structure-material-perfiles", label: "Structure · Perfiles de acero (Material)", group: "Sitio Structure", division: "Innovation", defaultSrc: "/geu-structure-material-perfiles.jpg", dims: "1024 × 1536 px" },
  { key: "innovation-principal", label: "Innovation · Imagen de portada del video", group: "Autoservicio · Inicio", division: "Innovation", defaultSrc: "/geu-innovation-hero.png", dims: "1920 × 1080 px" },
  { key: "innovation-hero-video", label: "Innovation · Video hero", group: "Autoservicio · Inicio", division: "Innovation", defaultSrc: "/geu-innovation-hero.mp4", dims: "1920 × 1080 px" },
  { key: "innovation-sistema-banner", label: "Innovation · Banner sección Sistema", group: "Autoservicio · Inicio", division: "Innovation", defaultSrc: "/geu-innovation-support-banner.jpg", dims: "1672 × 941 px" },
  { key: "innovation-tarjeta-autoservicio", label: "Innovation · Tarjeta Autoservicio 24/7", group: "Autoservicio · Inicio", division: "Innovation", defaultSrc: "/geu-innovation-card-autoservicio.jpg", dims: "1000 × 1000 px" },
  { key: "innovation-tarjeta-pago", label: "Innovation · Tarjeta Pago sin contacto", group: "Autoservicio · Inicio", division: "Innovation", defaultSrc: "/geu-innovation-card-pago.jpg", dims: "1000 × 1000 px" },
  { key: "innovation-tarjeta-asistente", label: "Innovation · Tarjeta Asistente GEU", group: "Autoservicio · Inicio", division: "Innovation", defaultSrc: "/geu-innovation-card-asistente.png", dims: "1000 × 1000 px" },
  { key: "innovation-tarjeta-espacios", label: "Innovation · Tarjeta Espacios colaborativos", group: "Autoservicio · Inicio", division: "Innovation", defaultSrc: "/geu-innovation-brand-banner.jpg", dims: "1000 × 1000 px" },
  { key: "innovation-oferta-1", label: "Innovation · Oferta 1", group: "Autoservicio · Ofertas y destacadas", division: "Innovation", defaultSrc: "/innovation-hero-banner.jpg", dims: "1024 × 1792 px" },
  { key: "innovation-oferta-2", label: "Innovation · Oferta 2", group: "Autoservicio · Ofertas y destacadas", division: "Innovation", defaultSrc: "/home-innovation.png", dims: "1024 × 1792 px" },
  { key: "innovation-oferta-3", label: "Innovation · Oferta 3", group: "Autoservicio · Ofertas y destacadas", division: "Innovation", defaultSrc: "/cauchos-industria-banner.jpg", dims: "1024 × 1792 px" },
  { key: "innovation-oferta-4", label: "Innovation · Oferta 4", group: "Autoservicio · Ofertas y destacadas", division: "Innovation", defaultSrc: "/innovation-hero-banner.jpg", dims: "1024 × 1792 px" },
  { key: "innovation-destacada-1", label: "Innovation · Destacada 1", group: "Autoservicio · Ofertas y destacadas", division: "Innovation", defaultSrc: "/innovation-destacada-1.jpg", dims: "1792 × 1024 px" },
  { key: "innovation-destacada-2", label: "Innovation · Destacada 2", group: "Autoservicio · Ofertas y destacadas", division: "Innovation", defaultSrc: "/innovation-destacada-2.jpg", dims: "1792 × 1024 px" },
  { key: "innovation-destacada-3", label: "Innovation · Destacada 3", group: "Autoservicio · Ofertas y destacadas", division: "Innovation", defaultSrc: "/innovation-destacada-3.jpg", dims: "1792 × 1024 px" },
  { key: "innovation-destacada-4", label: "Innovation · Destacada 4", group: "Autoservicio · Ofertas y destacadas", division: "Innovation", defaultSrc: "/innovation-destacada-4.jpg", dims: "1792 × 1024 px" },
  { key: "estufas-proyecto-1", label: "Estufas · Encuentro con la comunidad", group: "Estufas", division: "Innovation", defaultSrc: "/geu-innovation-project-1.jpg", dims: "1000 × 1000 px" },
  { key: "estufas-proyecto-2", label: "Estufas · Transporte hasta la vereda", group: "Estufas", division: "Innovation", defaultSrc: "/geu-innovation-project-2.jpg", dims: "1000 × 1000 px" },
  { key: "estufas-proyecto-3", label: "Estufas · Instalación y capacitación", group: "Estufas", division: "Innovation", defaultSrc: "/geu-innovation-project-3.png", dims: "1000 × 1000 px" },
  { key: "estufas-proyecto-4", label: "Estufas · Estufa ecoeficiente GEU", group: "Estufas", division: "Innovation", defaultSrc: "/geu-innovation-project-4.png", dims: "1000 × 1000 px" },
  { key: "estufas-proyecto-5", label: "Estufas · Acompañamiento en sitio", group: "Estufas", division: "Innovation", defaultSrc: "/geu-innovation-project-5.png", dims: "1000 × 1000 px" },
  { key: "estufas-proyecto-6", label: "Estufas · Comunidad conectada", group: "Estufas", division: "Innovation", defaultSrc: "/geu-innovation-project-6.jpg", dims: "1000 × 1000 px" },
  { key: "estufas-fabrica-video", label: "Estufas · Video de fabricación", group: "Estufas", division: "Innovation", defaultSrc: "/geu-innovation-fabrica-video.mp4", dims: "1920 × 1080 px" },
  { key: "estufas-fabrica-video-poster", label: "Estufas · Portada del video de fabricación", group: "Estufas", division: "Innovation", defaultSrc: "/geu-innovation-fabrica-video.png", dims: "1920 × 1080 px" },
  { key: "estufas-fabrica-1", label: "Estufas · Corte y armado del chasis", group: "Estufas", division: "Innovation", defaultSrc: "/geu-innovation-fabrica-1.jpg", dims: "1000 × 1000 px" },
  { key: "estufas-fabrica-2", label: "Estufas · Soldadura estructural", group: "Estufas", division: "Innovation", defaultSrc: "/geu-innovation-fabrica-2.jpg", dims: "1000 × 1000 px" },
  { key: "estufas-fabrica-3", label: "Estufas · Ensamble de puertas y detalles", group: "Estufas", division: "Innovation", defaultSrc: "/geu-innovation-fabrica-3.jpg", dims: "1000 × 1000 px" },
  { key: "estufas-fabrica-4", label: "Estufas · Acabados y pintura", group: "Estufas", division: "Innovation", defaultSrc: "/geu-innovation-fabrica-4.jpg", dims: "1000 × 1000 px" },
  { key: "estufas-fabrica-5", label: "Estufas · Control de calidad", group: "Estufas", division: "Innovation", defaultSrc: "/geu-innovation-fabrica-5.jpg", dims: "1000 × 1000 px" },
  { key: "estufas-fabrica-6", label: "Estufas · Producto terminado", group: "Estufas", division: "Innovation", defaultSrc: "/geu-innovation-fabrica-6.jpg", dims: "1000 × 1000 px" },
  { key: "estufas-contacto-fondo", label: "Estufas · Banner de contacto", group: "Estufas", division: "Innovation", defaultSrc: "/geu-innovation-project-6.jpg", dims: "1672 × 941 px" },
  { key: "doypack-hero-video", label: "Doypack · Video principal", group: "Doypack", division: "Innovation", defaultSrc: "/geu-doypack-hero.mp4", dims: "1920 × 1080 px" },
  { key: "doypack-galeria-1", label: "Doypack · Galería · Noche de juegos", group: "Doypack", division: "Innovation", defaultSrc: "/geu-doypack-strip-home.jpg", dims: "1600 × 1000 px" },
  { key: "doypack-galeria-2", label: "Doypack · Galería · Festival de música", group: "Doypack", division: "Innovation", defaultSrc: "/geu-doypack-festival.jpg", dims: "1600 × 1000 px" },
  { key: "doypack-galeria-3", label: "Doypack · Galería · Finca", group: "Doypack", division: "Innovation", defaultSrc: "/geu-doypack-strip-rural.jpg", dims: "1600 × 1000 px" },
  { key: "doypack-producto", label: "Doypack · Producto principal", group: "Doypack", division: "Innovation", defaultSrc: "/geu-doypack-product.jpg", dims: "1000 × 1250 px" },
  { key: "doypack-tapa-detalle", label: "Doypack · Detalle de la tapa", group: "Doypack", division: "Innovation", defaultSrc: "/geu-doypack-tapa-detalle.jpg", dims: "600 × 600 px" },
  { key: "doypack-skate-main", label: "Doypack · Persona patinando", group: "Doypack", division: "Innovation", defaultSrc: "/geu-doypack-skate-main.jpg", dims: "1600 × 1000 px" },
  { key: "doypack-skate-detail", label: "Doypack · Detalle en el cinturón", group: "Doypack", division: "Innovation", defaultSrc: "/geu-doypack-skate-detail.jpg", dims: "600 × 600 px" },
  { key: "doypack-cierre-festival", label: "Doypack · Banner de cierre", group: "Doypack", division: "Innovation", defaultSrc: "/geu-doypack-festival.jpg", dims: "2100 × 900 px" },
  { key: "plastic-principal", label: "Plastic · Banner principal", group: "Página de inicio", division: "Plastic", defaultSrc: "/geu-plastic-main-banner.jpg", dims: "1632 × 612 px" },
  { key: "plastic-principal-movil", label: "Plastic · Banner principal (versión móvil)", group: "Página de inicio", division: "Plastic", defaultSrc: "/geu-plastic-main-banner.jpg", dims: "1024 × 1024 px", isMobile: true },
  { key: "plastic-marcas-promo", label: "Plastic · Promociones y marcas", group: "Página de inicio", division: "Plastic", defaultSrc: "/geu-plastic-main-banner.jpg", dims: "2048 × 768 px" },
  { key: "plastic-cierre", label: "Plastic · Banner de cierre", group: "Página de inicio", division: "Plastic", defaultSrc: "/geu-plastic-main-banner.jpg", dims: "1920 × 217 px" },
  { key: "plastic-cierre-movil", label: "Plastic · Banner de cierre (versión móvil)", group: "Página de inicio", division: "Plastic", defaultSrc: "/geu-plastic-main-banner.jpg", dims: "800 × 360 px", isMobile: true },
  { key: "plastic-banner-categorias", label: "Banner de categorías", group: "Página de categorías", division: "Plastic", defaultSrc: "/geu-plastic-main-banner.jpg", dims: "1920 × 217 px" },
  { key: "plastic-banner-categorias-movil", label: "Banner de categorías (versión móvil)", group: "Página de categorías", division: "Plastic", defaultSrc: "/geu-plastic-main-banner.jpg", dims: "800 × 360 px", isMobile: true },
  { key: "plastic-oferta-1", label: "Plastic · Oferta 1", group: "Ofertas", division: "Plastic", defaultSrc: "/plastic-oferta-1.jpg", dims: "1024 × 1792 px" },
  { key: "plastic-oferta-2", label: "Plastic · Oferta 2", group: "Ofertas", division: "Plastic", defaultSrc: "/plastic-oferta-2.jpg", dims: "1024 × 1792 px" },
  { key: "plastic-oferta-3", label: "Plastic · Oferta 3", group: "Ofertas", division: "Plastic", defaultSrc: "/plastic-oferta-3.jpg", dims: "1024 × 1792 px" },
  { key: "plastic-oferta-4", label: "Plastic · Oferta 4", group: "Ofertas", division: "Plastic", defaultSrc: "/plastic-oferta-4.jpg", dims: "1024 × 1792 px" },
  { key: "plastic-destacada-1", label: "Plastic · Destacada 1", group: "Marcas destacadas", division: "Plastic", defaultSrc: "/plastic-destacada-1.jpg", dims: "1792 × 1024 px" },
  { key: "plastic-destacada-2", label: "Plastic · Destacada 2", group: "Marcas destacadas", division: "Plastic", defaultSrc: "/plastic-destacada-2.jpg", dims: "1792 × 1024 px" },
  { key: "plastic-destacada-3", label: "Plastic · Destacada 3", group: "Marcas destacadas", division: "Plastic", defaultSrc: "/plastic-destacada-3.jpg", dims: "1792 × 1024 px" },
  { key: "plastic-destacada-4", label: "Plastic · Destacada 4", group: "Marcas destacadas", division: "Plastic", defaultSrc: "/plastic-destacada-4.jpg", dims: "1792 × 1024 px" },
  { key: "plastic-nosotros-1", label: "Nosotros · Destacada 1", group: "Nosotros", division: "Plastic", defaultSrc: "/plastic-destacada-1.jpg", dims: "900 × 675 px" },
  { key: "plastic-nosotros-2", label: "Nosotros · Destacada 2", group: "Nosotros", division: "Plastic", defaultSrc: "/plastic-destacada-2.jpg", dims: "900 × 675 px" },
  { key: "plastic-nosotros-3", label: "Nosotros · Destacada 3", group: "Nosotros", division: "Plastic", defaultSrc: "/plastic-destacada-3.jpg", dims: "900 × 675 px" },
  { key: "plastic-nosotros-4", label: "Nosotros · Destacada 4", group: "Nosotros", division: "Plastic", defaultSrc: "/plastic-destacada-4.jpg", dims: "900 × 675 px" },
  { key: "plastic-categoria-pvc-rigido", label: "Categoría · Extrusión en PVC Rígido", group: "Categorías", division: "Plastic", defaultSrc: "/home-plastic.png", dims: "600 × 600 px" },
  { key: "plastic-categoria-pvc-flexible", label: "Categoría · Extrusión en PVC Flexible", group: "Categorías", division: "Plastic", defaultSrc: "/home-plastic.png", dims: "600 × 600 px" },
  { key: "plastic-categoria-empaques-magneticos", label: "Categoría · Desarrollo de empaques magnéticos", group: "Categorías", division: "Plastic", defaultSrc: "/home-plastic.png", dims: "600 × 600 px" },
  { key: "plastic-categoria-cintas-magneticas", label: "Categoría · Desarrollo de cintas magnéticas", group: "Categorías", division: "Plastic", defaultSrc: "/home-plastic.png", dims: "600 × 600 px" },
  { key: "plastic-categoria-ensamble-puertas-encimeras", label: "Categoría · Procesos de ensamble de puertas y encimeras", group: "Categorías", division: "Plastic", defaultSrc: "/home-plastic.png", dims: "600 × 600 px" },
  { key: "plastic-categoria-perfileria-hidroponia", label: "Categoría · Perfilería para hidroponía", group: "Categorías", division: "Plastic", defaultSrc: "/home-plastic.png", dims: "600 × 600 px" },
  { key: "plastic-categoria-perfileria-construccion", label: "Categoría · Perfilería para construcción", group: "Categorías", division: "Plastic", defaultSrc: "/home-plastic.png", dims: "600 × 600 px" },
  { key: "plastic-categoria-perfileria-carroceria", label: "Categoría · Perfilería para carrocería", group: "Categorías", division: "Plastic", defaultSrc: "/home-plastic.png", dims: "600 × 600 px" },
  // ---- Energy · Tienda (home) ----
  { key: "energy-tienda-principal", label: "Energy · Banner principal", group: "Página de inicio", division: "Energy", defaultSrc: "/energy-hero-banner.jpg", dims: "1632 × 612 px" },
  { key: "energy-tienda-principal-movil", label: "Energy · Banner principal (versión móvil)", group: "Página de inicio", division: "Energy", defaultSrc: "/energy-hero-banner.jpg", dims: "1024 × 1024 px", isMobile: true },
  { key: "energy-marcas-promo", label: "Energy · Promociones y soluciones", group: "Página de inicio", division: "Energy", defaultSrc: "/geu-energy-structures-banner.png", dims: "2048 × 768 px" },
  { key: "energy-cierre", label: "Energy · Banner de cierre", group: "Página de inicio", division: "Energy", defaultSrc: "/geu-energy-structures-banner.png", dims: "1920 × 217 px" },
  { key: "energy-cierre-movil", label: "Energy · Banner de cierre (versión móvil)", group: "Página de inicio", division: "Energy", defaultSrc: "/geu-energy-structures-banner.png", dims: "800 × 360 px", isMobile: true },
  { key: "energy-categoria-paneles-solares", label: "Categoría · Paneles solares", group: "Categorías", division: "Energy", defaultSrc: "/home-energy.png", dims: "600 × 600 px" },
  { key: "energy-categoria-inversores", label: "Categoría · Inversores", group: "Categorías", division: "Energy", defaultSrc: "/home-energy.png", dims: "600 × 600 px" },
  { key: "energy-categoria-baterias-respaldo", label: "Categoría · Baterías y respaldo", group: "Categorías", division: "Energy", defaultSrc: "/home-energy.png", dims: "600 × 600 px" },
  { key: "energy-categoria-estructuras-montaje", label: "Categoría · Estructuras de montaje", group: "Categorías", division: "Energy", defaultSrc: "/home-energy.png", dims: "600 × 600 px" },
  { key: "energy-categoria-cableado-conectores", label: "Categoría · Cableado y conectores", group: "Categorías", division: "Energy", defaultSrc: "/home-energy.png", dims: "600 × 600 px" },
  { key: "energy-categoria-controladores-carga", label: "Categoría · Controladores de carga", group: "Categorías", division: "Energy", defaultSrc: "/home-energy.png", dims: "600 × 600 px" },
  { key: "energy-categoria-medicion-monitoreo", label: "Categoría · Medición y monitoreo", group: "Categorías", division: "Energy", defaultSrc: "/home-energy.png", dims: "600 × 600 px" },
  { key: "energy-categoria-accesorios-instalacion", label: "Categoría · Accesorios e instalación", group: "Categorías", division: "Energy", defaultSrc: "/home-energy.png", dims: "600 × 600 px" },
  { key: "energy-oferta-1", label: "Energy · Oferta 1", group: "Ofertas", division: "Energy", defaultSrc: "/energy-oferta-paneles-solares.png", dims: "1024 × 1792 px" },
  { key: "energy-oferta-2", label: "Energy · Oferta 2", group: "Ofertas", division: "Energy", defaultSrc: "/energy-oferta-baterias-respaldo.png", dims: "1024 × 1792 px" },
  { key: "energy-oferta-3", label: "Energy · Oferta 3", group: "Ofertas", division: "Energy", defaultSrc: "/energy-oferta-estructuras-montaje.png", dims: "1024 × 1792 px" },
  { key: "energy-oferta-4", label: "Energy · Oferta 4", group: "Ofertas", division: "Energy", defaultSrc: "/energy-oferta-instalacion-proyecto.png", dims: "1024 × 1792 px" },
  { key: "energy-destacada-1", label: "Energy · Destacada 1", group: "Marcas destacadas", division: "Energy", defaultSrc: "/energy-aplicacion-residencial.jpg", dims: "1792 × 1024 px" },
  { key: "energy-destacada-2", label: "Energy · Destacada 2", group: "Marcas destacadas", division: "Energy", defaultSrc: "/energy-aplicacion-parque.jpg", dims: "1792 × 1024 px" },
  { key: "energy-destacada-3", label: "Energy · Destacada 3", group: "Marcas destacadas", division: "Energy", defaultSrc: "/energy-aplicacion-carport.jpg", dims: "1792 × 1024 px" },
  { key: "energy-destacada-4", label: "Energy · Destacada 4", group: "Marcas destacadas", division: "Energy", defaultSrc: "/geu-energy-impact.png", dims: "1792 × 1024 px" },

  // ---- Energy · Proyectos ----
  { key: "energy-principal", label: "Energy · Imagen de portada del video", group: "Proyectos", division: "Energy", defaultSrc: "/geu-energy-hero-field.png", dims: "1920 × 1080 px" },
  { key: "energy-hero-video", label: "Energy · Video hero", group: "Proyectos", division: "Energy", defaultSrc: "/geu-energy-hero-field.mp4", dims: "1920 × 1080 px" },
  { key: "energy-sistema-video", label: "Energy · Video sección Sistema", group: "Proyectos", division: "Energy", defaultSrc: "/geu-energy-project-house.mp4", dims: "1920 × 1080 px" },
  { key: "energy-sistema-video-poster", label: "Energy · Portada del video de Sistema", group: "Proyectos", division: "Energy", defaultSrc: "/geu-energy-project-house.jpg", dims: "1920 × 1080 px" },
  { key: "energy-estructuras-banner", label: "Energy · Banner de estructuras", group: "Proyectos", division: "Energy", defaultSrc: "/geu-energy-structures-banner.png", dims: "2400 × 800 px" },
  { key: "energy-contacto-fondo", label: "Energy · Fondo sección Gus", group: "Proyectos", division: "Energy", defaultSrc: "/geu-energy-gus-bg.jpg", dims: "1672 × 941 px" },
  { key: "energy-solucion-monoposte", label: "Energy · Estructura Monoposte", group: "Proyectos", division: "Energy", defaultSrc: "/energy-estructura-monoposte.jpg", dims: "1000 × 1000 px" },
  { key: "energy-solucion-biposte", label: "Energy · Estructura Biposte", group: "Proyectos", division: "Energy", defaultSrc: "/energy-estructura-biposte.jpg", dims: "1000 × 1000 px" },
  { key: "energy-solucion-chinesehat", label: "Energy · Estructura Chinese hat", group: "Proyectos", division: "Energy", defaultSrc: "/energy-estructura-chinesehat.jpg", dims: "1000 × 1000 px" },
  { key: "energy-solucion-carport", label: "Energy · Estructura Carport", group: "Proyectos", division: "Energy", defaultSrc: "/energy-estructura-carport.jpg", dims: "1000 × 1000 px" },

  // ---- GEU · Nosotros (corporativo) ----
  { key: "geu-nosotros-hero", label: "Nosotros · Fondo del héroe", group: "Nosotros", division: "GEU", defaultSrc: "/about-geu-logo-wall.jpg", dims: "1962 × 802 px" },
  { key: "geu-nosotros-ecosistema", label: "Nosotros · Imagen de ecosistema", group: "Nosotros", division: "GEU", defaultSrc: "/about-geu-ecosystem.jpg", dims: "1672 × 941 px" },
  { key: "geu-nosotros-contacto", label: "Nosotros · Fondo de cierre", group: "Nosotros", division: "GEU", defaultSrc: "/about-geu-industrial-night.jpg", dims: "1983 × 793 px" },
];

export type SiteImages = Record<string, string>;

export function resolveImage(key: string, siteImages: SiteImages): string {
  return siteImages[key] ?? IMAGE_SLOTS.find((s) => s.key === key)?.defaultSrc ?? "";
}

const VIDEO_EXTENSIONS = [".mp4", ".webm", ".mov"];

export function isVideoUrl(url: string): boolean {
  const path = url.split("?")[0].toLowerCase();
  return VIDEO_EXTENSIONS.some((ext) => path.endsWith(ext));
}
